### ISSUE TITLE
Ошибка из-за отсутствия поля update_id в данных вебхука YooKassa, которые не соответствуют формату Telegram

### ISSUE THREAD

**Issue by KoPobkaTopta** [Vladless/Solo_bot#111]
2024-12-07 18:44:19 | ERROR | base_events:default_exception_handler:1758 | Task exception was never retrieved
future: <Task finished name='Task-55' coro=<BaseRequestHandler._background_feed_update() done, defined at /root/Solo_bot/venv/lib/python3.10/site-packages/aiogram/webhook/aiohttp_server.py:137> exception=1 validation error for Update
update_id
  Field required [type=missing, input_value={'type': 'notification', ...'yookassa_sdk_python'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing>
Traceback (most recent call last):

> File "/root/Solo_bot/venv/lib/python3.10/site-packages/aiogram/webhook/aiohttp_server.py", line 138, in _background_feed_update
    result = await self.dispatcher.feed_raw_update(bot=bot, update=update, **self.data)
                   │    │          │                   │           │         │    └ {}
                   │    │          │                   │           │         └ <aiogram.webhook.aiohttp_server.SimpleRequestHandler object at 0x7f5175b0de40>
                   │    │          │                   │           └ {'type': 'notification', 'event': 'payment.succeeded', 'object': {'id': '2e02d-000f-5000-b000-1dc2ea3', 'status': 'su...
                   │    │          │                   └ <aiogram.client.bot.Bot object at 0x7f51767935b0>
                   │    │          └ <function Dispatcher.feed_raw_update at 0x7f5176889cf0>
                   │    └ <Dispatcher '0x7f517672b460'>
                   └ <aiogram.webhook.aiohttp_server.SimpleRequestHandler object at 0x7f5175b0de40>
  File "/root/Solo_bot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 188, in feed_raw_update
    parsed_update = Update.model_validate(update, context={"bot": bot})
                    │      │              │                       └ <aiogram.client.bot.Bot object at 0x7f51767935b0>
                    │      │              └ {'type': 'notification', 'event': 'payment.succeeded', 'object': {'id': '2ee42d-000f-00-b000-1dc2e823', 'status': 'su...
                    │      └ <classmethod(<function BaseModel.model_validate at 0x7f5179895900>)>
                    └ <class 'aiogram.types.update.Update'>
  File "/root/Solo_bot/venv/lib/python3.10/site-packages/pydantic/main.py", line 596, in model_validate
    return cls.__pydantic_validator__.validate_python(
           │   │                      └ <method 'validate_python' of 'pydantic_core._pydantic_core.SchemaValidator' objects>
           │   └ SchemaValidator(title="Update", validator=Model(
           │         ModelValidator {
           │             revalidate: Never,
           │             validator: FunctionB...
           └ <class 'aiogram.types.update.Update'>

pydantic_core._pydantic_core.ValidationError: 1 validation error for Update
update_id
  Field required [type=missing, input_value={'type': 'notification', ...'yookassa_sdk_python'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing

**Comment by Vladless** [comment]
Здравствуйте! Ошибка не в коде бота, а в неправильной настройке бота.

Важно придерживаться гайда, который мы предоставляем после покупки и прислушиваться к рекомендациям разработчика.

**Comment by KoPobkaTopta** [comment]
Ну хотя бы намекни что ни так, вродь все идеально сделано
